apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-validator-monitor
  namespace: payflow
spec:
  selector:
    matchLabels:
      app: transaction-validator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
