apiVersion: v1
kind: Service
metadata:
  name: transaction-validator-service
  namespace: payflow
  labels:
    app: transaction-validator
spec:
  type: NodePort
  selector:
    app: transaction-validator
    version: blue  # Por defecto apunta a BLUE
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  sessionAffinity: None